name: Deploy

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            
            - name: Check files
              run: |
                if [ ! -f "index.html" ]; then
                  echo "::error::index.html not found"
                  exit 1
                fi
            
            - name: Setup Pages
              uses: actions/configure-pages@v3
              
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                path: '.'
                
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v2